// Generated by CoffeeScript 1.3.3
(function() {
  var es, httpreq, root, _ref;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  es = (typeof require === "function" ? require('./extstorage') : void 0) || root;

  httpreq = (typeof require === "function" ? (_ref = require("xmlhttprequest")) != null ? _ref.XMLHttpRequest : void 0 : void 0) || XMLHttpRequest;

  root.WeakSpecPopulator = (function() {

    function WeakSpecPopulator(file) {
      this.file = file;
      this.storage = new es.ExtStorage();
      this.load(this.read(this.file));
      this.dbPopulate();
    }

    WeakSpecPopulator.prototype.read = function(file) {
      var r;
      r = new httpreq();
      r.open("GET", file, false);
      r.send(null);
      return r.responseText;
    };

    WeakSpecPopulator.prototype.load = function(code) {
      if (code.length === 0) {
        throw new Error("Was '" + this.file + "' even read?");
      }
      try {
        eval(code);
        return this.spec = weakspec;
      } catch (e) {
        throw new Error("" + this.file + " contains errors: " + e.message);
      }
    };

    WeakSpecPopulator.prototype.dbPopulate = function() {
      var group, instr, name, prefs, _ref1, _results;
      if (!this.spec) {
        throw new Error('@spec variable does not contain a weakspec');
      }
      _ref1 = this.spec;
      _results = [];
      for (group in _ref1) {
        prefs = _ref1[group];
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (name in prefs) {
            instr = prefs[name];
            if ((this.storage.get(group, name)) === null) {
              _results1.push(this.storage.set(group, name, instr["default"]));
            } else {
              _results1.push(void 0);
            }
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    return WeakSpecPopulator;

  })();

}).call(this);
